// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVKJ1yhVaJwMtCpWYXUuP0ekBcekRS0o4',
    appId: '1:214727902300:web:23b005e965e129e05d1299',
    messagingSenderId: '214727902300',
    projectId: 'todolist-app-2cca8',
    authDomain: 'todolist-app-2cca8.firebaseapp.com',
    storageBucket: 'todolist-app-2cca8.firebasestorage.app',
    measurementId: 'G-JHPR8BR237',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt7dQPtKAjeMnC5uTUyJpk0fHRyhKg0LQ',
    appId: '1:214727902300:android:44a844bb765bf0115d1299',
    messagingSenderId: '214727902300',
    projectId: 'todolist-app-2cca8',
    storageBucket: 'todolist-app-2cca8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Nbx2l1rP9pO9anTBhcq4wMdMCxXulfI',
    appId: '1:214727902300:ios:5c038db4bb3e15ba5d1299',
    messagingSenderId: '214727902300',
    projectId: 'todolist-app-2cca8',
    storageBucket: 'todolist-app-2cca8.firebasestorage.app',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Nbx2l1rP9pO9anTBhcq4wMdMCxXulfI',
    appId: '1:214727902300:ios:5c038db4bb3e15ba5d1299',
    messagingSenderId: '214727902300',
    projectId: 'todolist-app-2cca8',
    storageBucket: 'todolist-app-2cca8.firebasestorage.app',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVKJ1yhVaJwMtCpWYXUuP0ekBcekRS0o4',
    appId: '1:214727902300:web:7d8659b46eaad0685d1299',
    messagingSenderId: '214727902300',
    projectId: 'todolist-app-2cca8',
    authDomain: 'todolist-app-2cca8.firebaseapp.com',
    storageBucket: 'todolist-app-2cca8.firebasestorage.app',
    measurementId: 'G-60Y9FNL2ML',
  );
}
